package com.fittrack.fittrackbackend.enums;

public enum WorkoutExercise {
    // Strength
    BENCH_PRESS, INCLINE_BENCH_PRESS, DECLINE_BENCH_PRESS, CHEST_FLY, PUSH_UPS,
    LAT_PULLDOWN, PULL_UPS, SEATED_ROW, BARBELL_ROW, DEADLIFT,
    SHOULDER_PRESS, LATERAL_RAISE, FRONT_RAISE, REAR_DELT_FLY, ARNOLD_PRESS,
    BARBELL_CURL, DUMBBELL_CURL, HAMMER_CURL, CABLE_CURL,
    PUSHDOWN, SKULL_CRUSHERS, OVERHEAD_EXTENSION, BENCH_DIPS,
    SQUATS, LEG_PRESS, LUNGES, ROMANIAN_DEADLIFT, LEG_EXTENSION, HAMSTRING_CURL, CALF_RAISE,
    CRUNCHES, HANGING_LEG_RAISE, RUSSIAN_TWIST, PLANK,
    
    // Cardio
    WALKING, JOGGING, RUNNING, CYCLING, STATIONARY_BIKE, ELLIPTICAL, SKIPPING_ROPE, SWIMMING, STAIR_CLIMBER, ROWING, TREADMILL,
    
    // Yoga
    HATHA_YOGA, POWER_YOGA, VINYASA, ASHTANGA, SURYA_NAMASKAR, STRETCHING
}
